//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contents
    {
        public int ContentId { get; set; }
        public string Position { get; set; }
        public string Publish { get; set; }
        public string ShowTitle { get; set; }
        public string AccessLevel { get; set; }
        public string Text { get; set; }
        public string Title { get; set; }
    }
}
